version: '3.8'

services:

  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    environment:
      - MONGODB_URL=mongodb://mongo:27017
      - MONGODB_DB_NAME=webnovel_manager
      - DEBUG=1 # 1 para usar Google Translate, 0 para DeepL
      - DEEPL_API_KEY=tu_api_key_aqui
      - TARGET_LANGUAGE=ES
    networks:
      - default
      - mongodb_default

networks:
  default:
    name: webnovel-manager_default
  mongodb_default:
    external: true
